apiVersion: v1
kind: Service
metadata:
  name: ad
  namespace: dailybugle
spec:
  selector: { app: ad }
  ports: [{ port: 4004, targetPort: 4004 }]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ad
  namespace: dailybugle
spec:
  replicas: 1
  selector: { matchLabels: { app: ad } }
  template:
    metadata: { labels: { app: ad } }
    spec:
      containers:
        - name: ad
          image: dailybugle:latest
          imagePullPolicy: IfNotPresent
          command: ["node","backend/ad.js"]
          envFrom: [{ configMapRef: { name: app-env } }]
          ports: [{ containerPort: 4004 }]
          livenessProbe:  { tcpSocket: { port: 4004 }, initialDelaySeconds: 5, periodSeconds: 10 }
          readinessProbe: { tcpSocket: { port: 4004 }, initialDelaySeconds: 3, periodSeconds: 5 }
