apiVersion: v1
kind: Service
metadata:
  name: article
  namespace: dailybugle
spec:
  selector: { app: article }
  ports: [{ port: 4001, targetPort: 4001 }]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: article
  namespace: dailybugle
spec:
  replicas: 1
  selector: { matchLabels: { app: article } }
  template:
    metadata: { labels: { app: article } }
    spec:
      containers:
        - name: article
          image: dailybugle:latest
          imagePullPolicy: IfNotPresent
          command: ["node","backend/article.js"]
          envFrom: [{ configMapRef: { name: app-env } }]
          ports: [{ containerPort: 4001 }]
          livenessProbe:  { tcpSocket: { port: 4001 }, initialDelaySeconds: 5, periodSeconds: 10 }
          readinessProbe: { tcpSocket: { port: 4001 }, initialDelaySeconds: 3, periodSeconds: 5 }