apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: dailybugle
spec:
  selector: { app: auth }
  ports: [{ port: 4000, targetPort: 4000 }]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: dailybugle
spec:
  replicas: 1
  selector: { matchLabels: { app: auth } }
  template:
    metadata: { labels: { app: auth } }
    spec:
      initContainers:
        - name: wait-for-mongodb
          image: busybox:1.35
          command: ['sh', '-c', 'until nc -z mongodb 27017; do echo waiting for mongodb; sleep 2; done']
      containers:
        - name: auth
          image: dailybugle:latest
          imagePullPolicy: IfNotPresent
          command: ["node","backend/auth.js"]
          envFrom: [{ configMapRef: { name: app-env } }]
          ports: [{ containerPort: 4000 }]
          livenessProbe:  { tcpSocket: { port: 4000 }, initialDelaySeconds: 5, periodSeconds: 10 }
          readinessProbe: { tcpSocket: { port: 4000 }, initialDelaySeconds: 3, periodSeconds: 5 }