apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: dailybugle
spec:
  selector: { app: mongodb }
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: dailybugle
spec:
  serviceName: mongodb
  replicas: 1
  selector: { matchLabels: { app: mongodb } }
  template:
    metadata: { labels: { app: mongodb } }
    spec:
      containers:
        - name: mongod
          image: mongo:7
          ports: [{ containerPort: 27017 }]
          volumeMounts:
            - name: data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata: { name: data }
      spec:
        accessModes: ["ReadWriteOnce"]
        resources: { requests: { storage: 2Gi } }