apiVersion: v1
kind: Service
metadata:
  name: search
  namespace: dailybugle
spec:
  selector: { app: search }
  ports: [{ port: 4003, targetPort: 4003 }]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
  namespace: dailybugle
spec:
  replicas: 1
  selector: { matchLabels: { app: search } }
  template:
    metadata: { labels: { app: search } }
    spec:
      containers:
        - name: search
          image: dailybugle:latest
          imagePullPolicy: IfNotPresent
          command: ["node","backend/search.js"]
          envFrom: [{ configMapRef: { name: app-env } }]
          ports: [{ containerPort: 4003 }]
          livenessProbe:  { tcpSocket: { port: 4003 }, initialDelaySeconds: 5, periodSeconds: 10 }
          readinessProbe: { tcpSocket: { port: 4003 }, initialDelaySeconds: 3, periodSeconds: 5 }
